// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },

  modules: [
    '@nuxt/ui',
    '@nuxt/image',
    '@nuxt/fonts',
    '@nuxtjs/supabase',
    '@pinia/nuxt',
  ],

  fonts: {
    families: [
      { name: 'Satoshi', provider: 'fontshare', weights: [500, 700, 900] },
      { name: 'Inter', provider: 'google', weights: [400, 500, 600, 700] },
      { name: 'JetBrains Mono', provider: 'google', weights: [400, 500, 600] },
    ],
    defaults: {
      preload: true,
    },
  },

  css: ['~/assets/css/landing.css', '~/assets/css/app.css'],

  icon: {
    serverBundle: 'local',
    clientBundle: {
      icons: [
        'lucide:heart-pulse',
        'lucide:baby',
        'lucide:calendar-check',
        'lucide:shield-check',
        'lucide:users',
        'lucide:activity',
        'lucide:file-text',
        'lucide:bell',
        'lucide:settings',
        'lucide:bar-chart-3',
        'lucide:stethoscope',
        'lucide:menu',
        'lucide:x',
        'lucide:chevron-right',
        'lucide:arrow-right',
        'lucide:check',
        'lucide:phone',
        'lucide:mail',
        'lucide:map-pin',
        'lucide:user-x',
        'lucide:route-off',
        'lucide:pill',
        'lucide:phone-off',
        'lucide:help-circle',
        'lucide:alarm-clock-off',
        'lucide:folder-x',
        'lucide:brain',
        'lucide:route',
        'lucide:bell-ring',
        'lucide:palette',
        'lucide:layout-dashboard',
        'lucide:headphones',
        'lucide:footprints',
        'lucide:folder',
        'lucide:trending-up',
        'lucide:target',
        'lucide:globe',
        'lucide:landmark',
        'lucide:alert-triangle',
        'lucide:rocket',
        'lucide:flame',
        'lucide:phone-call',
        'lucide:graduation-cap',
        'lucide:chevron-down',
        'lucide:lock',
        'lucide:key-round',
        'lucide:scroll-text',
        'lucide:eye-off',
        'lucide:user-check',
        'lucide:file-check',
        'lucide:code-2',
        'lucide:file-code',
        'lucide:zap',
        'lucide:radio',
        'lucide:cloud',
        'lucide:git-branch',
        'lucide:bug',
        'lucide:search',
        'lucide:database',
        'lucide:server',
        'lucide:layout',
        'lucide:home',
        'lucide:log-out',
        'lucide:chevron-left',
        'lucide:clipboard-list',
        'lucide:syringe',
        'lucide:upload',
        'lucide:moon',
        'lucide:smile',
        'lucide:line-chart',
        'lucide:utensils',
        'lucide:trophy',
        'lucide:book-open',
        'lucide:message-circle',
        'lucide:video',
        'lucide:star',
        'lucide:send',
        'lucide:plus',
        'lucide:edit',
        'lucide:trash-2',
        'lucide:eye',
        'lucide:download',
        'lucide:copy',
        'lucide:share-2',
        'lucide:filter',
        'lucide:calendar',
        'lucide:clock',
        'lucide:map',
        'lucide:user',
        'lucide:user-plus',
        'lucide:heart',
        'lucide:shield',
        'lucide:info',
        'lucide:loader-2',
        'lucide:refresh-cw',
        'lucide:package',
        'lucide:test-tube',
        'lucide:smartphone',
        'lucide:check-square',
        'lucide:check-circle',
        'lucide:link',
        'lucide:minus',
        'lucide:mic',
        'lucide:mic-off',
        'lucide:camera',
        'lucide:camera-off',
        'lucide:thumbs-up',
        'lucide:thumbs-down',
        'lucide:trending-down',
        'lucide:minus-circle',
        'lucide:arrow-up-right',
        'lucide:arrow-down-right',
        'lucide:sparkles',
        'lucide:award',
        'lucide:timer',
        'lucide:inbox',
        'lucide:image',
        'lucide:file-plus',
        'lucide:grip-vertical',
        'lucide:circle-dot',
        'lucide:circle-check',
        'lucide:circle-x',
        'lucide:circle-alert',
        'lucide:building-2',
        'lucide:calendar-range',
        'lucide:plug',
        'lucide:network',
        'lucide:chevron-up',
        'lucide:move-right',
        'lucide:scan-line',
        'lucide:ruler',
        'lucide:weight',
        'lucide:apple',
        'lucide:bed',
        'lucide:sun',
        'lucide:coffee',
        'lucide:gift',
        'lucide:crown',
        'lucide:alarm-clock',
        'lucide:hand-heart',
      ],
    },
  },

  app: {
    pageTransition: { name: 'page-fade', mode: 'out-in' },
    head: {
      htmlAttrs: { lang: 'ru' },
      title: 'Family Care OS — Цифровой маршрут заботы',
      meta: [
        { name: 'description', content: 'Платформа под вашим брендом для частных клиник. Ведёт семью по маршруту наблюдения от зачатия до 2 лет ребёнка.' },
        { property: 'og:title', content: 'Family Care OS — Цифровой маршрут заботы' },
        { property: 'og:description', content: 'Платформа под вашим брендом для частных клиник. Маршрут от зачатия до 2 лет.' },
        { property: 'og:type', content: 'website' },
        { name: 'theme-color', content: '#8B7EC8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      ],
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
      ],
    },
  },

  runtimeConfig: {
    openaiApiKey: process.env.OPENAI_API_KEY || '',
    supabaseServiceKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
    resendApiKey: process.env.RESEND_API_KEY || '',
    public: {
      sentryDsn: process.env.SENTRY_DSN || '',
      posthogKey: process.env.POSTHOG_KEY || '',
    },
  },

  supabase: {
    url: process.env.SUPABASE_URL || '',
    key: process.env.SUPABASE_KEY || '',
    secretKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
    redirect: false, // We handle auth redirects in middleware
  },

  image: {
    sharp: {
      // Disable bundling sharp binaries — Vercel provides sharp natively
    },
  },

  nitro: {
    preset: 'vercel',
    prerender: {
      routes: ['/', '/for-clinics', '/for-families'],
    },
    routeRules: {
      '/_nuxt/**': {
        headers: {
          'Cache-Control': 'public, max-age=31536000, immutable',
        },
      },
      '/api/**': {
        headers: {
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'DENY',
          'X-XSS-Protection': '1; mode=block',
          'Referrer-Policy': 'strict-origin-when-cross-origin',
        },
      },
      '/**': {
        headers: {
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'SAMEORIGIN',
          'X-XSS-Protection': '1; mode=block',
          'Referrer-Policy': 'strict-origin-when-cross-origin',
          'Permissions-Policy': 'camera=(), microphone=(), geolocation=(self)',
          'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
        },
      },
    },
  },

  vite: {
    optimizeDeps: {
      include: ['echarts', 'cookie', '@supabase/ssr > cookie'],
    },
    ssr: {
      noExternal: [],
    },
  },
})
